name: test-oidc

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-blob:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login with managed identity via OIDC
        uses: azure/login@v1
        with:
          client-id: 87eb4352-8747-4079-9a13-39b60b6f6360
          tenant-id: fdd066e1-ee37-49bc-b08f-d0e152119b04
          subscription-id: 8d17ab28-a79a-43da-9862-b674b4a02687

      - name: Who am I
        run: az account show

      - name: List containers
        run: |
          az storage container list \
            --account-name iamazurelab3206a7f96 \
            --auth-mode login
            
      - name: storage blob download
        run: |
            az storage blob download \
              --account-name "/subscriptions/8d17ab28-a79a-43da-9862-b674b4a02687/resourceGroups/iam-azure-labs/providers/Microsoft.Storage/storageAccounts/iamazurelab3206a7f96" \
              --container-name flag \
              --name flag.txt \
              --file  flag.txt \
              --auth-mode login
      - name: cat flag
        run: |
          cat flag.txt
