name: test-oidc

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-blob:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login with managed identity via OIDC
        uses: azure/login@v1
        with:
          client-id: 87exxxxxx6360
          tenant-id: fddxxxxx9b04
          subscription-id: 8d1xxxxxxxxxxxxxx687

      - name: Who am I
        run: az account show

      - name: List containers
        run: |
          az storage container list \
            --account-name iamxxxxxxxxxxf96 \
            --auth-mode login
            
      - name: storage blob download
        run: |
            az storage blob download \
              --account-name "xxxxx" \
              --container-name flag \
              --name flag.txt \
              --file  flag.txt \
              --auth-mode login
      - name: cat flag
        run: |
          cat flag.txt
